#!/bin/sh

window_count=$(osascript -e 'tell application "System Events" to count windows of process "Google Chrome"')

if [ $window_count -eq 0 ]; then
    osascript -e 'tell application "Google Chrome"' \
        -e 'make new window' \
        -e 'activate' \
        -e "set URL of active tab of first window to $1" \
        -e 'end tell'
else
    osascript -e 'tell application "Google Chrome"' \
        -e 'make new tab at end of tabs of window 1' \
        -e 'activate' \
        -e "set URL of active tab of first window to $1" \
        -e 'end tell'
fi

